# site settings
title: Blacksuan19
subtitle:
email: abubakaryagob@@gmail.com
description: A place where i have my portfolio,  projects and random thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Blacksuan19
street_address:
city: Kuala Lumpur
state: Selangor
zip_code: 53100
country: Malaysia
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/blacksuan19
instagram_url: https://instagram.com/blacksuan19
# build settings
markdown: kramdown

sass:
  style: compressed
